### ISSUE TITLE
requirements make no sense

### ISSUE THREAD

**Issue by jbrucker** [KunKid-cmd/ku-polls#1]
https://github.com/KunKid-cmd/ku-polls/blob/045925ef0cbb261a92dc36e89dc8cc3862ce3413/requirements.txt#L2C21-L2C21

If you write `Django <= 4.2` then it is redundant to write `< 5.0`.

do you want to allow Django version 1.0?

**Comment by KunKid-cmd** [comment]
Thank you for telling me I'm fix it.
